#!/usr/bin/env node

const decks = Object.values(require('./products/decks.json'))

const totalDecks = decks.length
const importedDecks = decks.reduce((acc, { imported }) => acc + imported, 0)

console.log(`Imported: ${importedDecks}/${totalDecks} (${totalDecks - importedDecks} remaining)`)
